version: '3'

tasks:
  git-push:
    desc: Push the changes to repository
    cmds:
      - git pull
      - git add .
      - git commit -m "{{.CLI_ARGS}}"
      - git push

  ga-create-repo:
    desc: Run the Create Repo Pipeline
    cmds:
      - act -j create-repository -e .github/workflows/git/github/create-repo-inputs.json --pull=false --action-offline-mode